name: Semantic Release

on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history is required for proper commit analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create minimal package.json for semantic-release
        run: |
          # Create a minimal package.json if one doesn't exist
          if [ ! -f package.json ]; then
            echo '{}' > package.json
          fi

      - name: Install semantic-release and plugins
        run: |
          npm install semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/npm \
            @semantic-release/github \
            @semantic-release/git

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
